name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - test
    tags:
      - '*'
  workflow_dispatch:

jobs:
  dialyzer:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: setup
        id: setup
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.18.4'
          otp-version: '28.1'

      - name: mix-cache
        uses: actions/cache@v4
        id: mix-cache
        with:
          path: deps
          # yamllint disable-line rule:line-length
          key: ${{ runner.os }}-${{ steps.setup.outputs.otp-version }}-${{ steps.setup.outputs.elixir-version }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: mix-deps
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get

      - name: plt-cache
        uses: actions/cache@v4
        id: plt-cache
        with:
          path: plts
          key: ${{ runner.os }}-${{ steps.setup.outputs.otp-version }}-${{ steps.setup.outputs.elixir-version }}-plts

      - name: plt-create
        if: steps.plt-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p plts
          mix dialyzer --plt

      - name: dialyzer
        run: mix dialyzer

  quality_actions:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - run: yamllint .
        working-directory: .github

  quality_elixir:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: setup
        id: setup
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.18.4'
          otp-version: '28.1'

      - name: mix-cache
        uses: actions/cache@v4
        id: mix-cache
        with:
          path: deps
          # yamllint disable-line rule:line-length
          key: ${{ runner.os }}-${{ steps.setup.outputs.otp-version }}-${{ steps.setup.outputs.elixir-version }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: mix-deps
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get

      - name: check unused deps
        run: mix deps.unlock --check-unused

      - name: check for compiler warnings
        run: |
          mix deps.compile
          mix compile --warnings-as-errors

      - name: format
        run: mix format --check-formatted

      - name: credo
        run: mix credo --strict

  test:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: '1.11.4'
            otp: '24.3'
            cayley: 'v0.7.3'
          - elixir: '1.12.3'
            otp: '24.3'
            cayley: 'v0.7.4'
          - elixir: '1.13.4'
            otp: '24.3'
            cayley: 'v0.7.5'
          - elixir: '1.14.5'
            otp: '24.3'
            cayley: 'v0.7.6'
          - elixir: '1.15.7'
            otp: '25.3'
            cayley: 'v0.7.6'
          - elixir: '1.16.3'
            otp: '26.2'
            cayley: 'v0.7.6'
          - elixir: '1.17.3'
            otp: '27.3'
            cayley: 'v0.7.6'
          - elixir: '1.18.4'
            otp: '28.1'
            cayley: 'v0.7.6'

    services:
      cayley:
        image: cayleygraph/cayley:${{ matrix.cayley }}
        ports:
          - 64210:64210

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: setup
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: mix-cache
        uses: actions/cache@v4
        id: mix-cache
        with:
          path: deps
          # yamllint disable-line rule:line-length
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: mix-deps
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get

      - name: test
        run: mix coveralls
