name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.runs-on }}

    strategy:
      matrix:
        include:
          - elixir: '1.11.4'
            otp: '21.3'
            cayley: 'v0.7.3'
            runs-on: ubuntu-20.04
          - elixir: '1.12.3'
            otp: '22.3'
            cayley: 'v0.7.4'
            runs-on: ubuntu-20.04
          - elixir: '1.13.4'
            otp: '23.3'
            cayley: 'v0.7.5'
            runs-on: ubuntu-20.04
          - elixir: '1.14.3'
            otp: '24.3'
            cayley: 'v0.7.6'
            runs-on: ubuntu-22.04
          - elixir: '1.14.3'
            otp: '25.2'
            cayley: 'v0.7.6'
            runs-on: ubuntu-22.04

    services:
      cayley:
        image: cayleygraph/cayley:${{ matrix.cayley }}
        ports:
          - 64210:64210

    env:
      MIX_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v3

    - name: setup
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.otp }}

    - name: mix-cache
      uses: actions/cache@v3
      id: mix-cache
      with:
        path: deps
        key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

    - name: mix-deps
      if: steps.mix-cache.outputs.cache-hit != 'true'
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get

    - name: test
      run: mix coveralls.github
